name: Generate README
on:
  workflow_call:
    inputs:
      wait-for-commits:
        description: "Number of commits to wait for"
        required: false
        type: number
        default: 10
      template-file:
        description: "Template file"
        required: false
        type: string
        default: "README.tmpl.md"
      output-file:
        description: "Output file"
        required: false
        type: string
        default: "README.md"
      header:
        description: "Cloc header"
        required: false
        type: string
        default: "Lines of code"
  # push:
  # pull_request:
  #   paths:
  #     - "README.md" # This isn't needed, but it's a good sanity check
  #     - "README.tmpl.md"
  # workflow_dispatch:
jobs:
  generate-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Hack to add one to the commit count
        env:
          COMMIT_COUNT: ${{ inputs.wait-for-commits }}
        run: |
          echo "wait_for_commits_plus_one=$((COMMIT_COUNT + 1))" >> $GITHUB_ENV

      - uses: actions/checkout@master
        with: # We need to fetch enough commits to check if we've waited long enough
          fetch-depth: ${{ env.wait_for_commits_plus_one }}
      - name: Check if we've waited long enough (${{ inputs.wait-for-commits }}+ commits)
        id: commit-count
        continue-on-error: true
        run: |
          [ '${{ github.event_name }}' != 'workflow_dispatch' ] || exit 0
          last_sha=$(git log --oneline --format=format:%H --grep="^chore: Generate README$" -1)
          echo "last_sha=$last_sha"
          if [ -n "$last_sha" ]; then # success if last_sha is empty
            count=$(git rev-list $last_sha..HEAD --count)
            echo "count=$count"
            [ $count -gt ${{ inputs.wait-for-commits }} ] || exit 1
          fi
      - name: Initialize ${{ inputs.output-file }}
        if: ${{ steps.commit-count.outcome == 'success' }}
        run: |
          [ -f ${{ inputs.template-file }} ] || cp ${{ inputs.output-file }} ${{inputs.template-file}}
          printf '%s\n' "<!-- This file is generated from ${{ inputs.template-file }} -->" >> ${{ inputs.output-file }}
          cat ${{ inputs.template-file }} >> ${{ inputs.output-file }}

      - name: CLOC
        if: ${{ steps.commit-count.outcome == 'success' }}
        uses: docker://aldanial/cloc
        with: # Exclude YAML to avoid counting lock files
          args: ${{ github.sha }} --md --report-file=cloc.md --hide-rate --exclude-lang=YAML

      - name: output cloc.md
        if: ${{ steps.commit-count.outcome == 'success' }}
        run: cat cloc.md

      # Note: initial newline is required because git files don't end with one
      - name: Update ${{ inputs.output-file }}
        if: ${{ steps.commit-count.outcome == 'success' }}
        run: |
          printf '\n' >> ${{ inputs.output-file }}
          printf '%s\n' '### ${{ inputs.header }}' "<sup><sub>Generated at commit ${{ github.sha }}</sub></sup>" >> ${{ inputs.output-file }}
          cat cloc.md >> ${{ inputs.output-file }}
          rm cloc.md
      - name: Commit ${{ inputs.output-file }}
        uses: stefanzweifel/git-auto-commit-action@v4
        if: ${{ steps.commit-count.outcome == 'success' }}
        with:
          commit_message: "chore: Generate ${{ inputs.output-file }}"
          # Note: README.tmpl.md is needed in the first case
          file_pattern: ${{ inputs.output-file }} ${{ inputs.template-file }}
